[project]
name = "camera-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytz>=2025.2",
    "requests>=2.32.3",
    "uiprotect>=7.6.0",
    "openai>=1.40.0",
]
